# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(400, 152)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(about.sizePolicy().hasHeightForWidth())
        about.setSizePolicy(sizePolicy)
        about.setMinimumSize(QtCore.QSize(400, 152))
        about.setMaximumSize(QtCore.QSize(400, 152))
        self.horizontalLayout = QtWidgets.QHBoxLayout(about)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.aboutlay = QtWidgets.QVBoxLayout()
        self.aboutlay.setSpacing(0)
        self.aboutlay.setObjectName("aboutlay")
        self.aboutlay2 = QtWidgets.QWidget(about)
        self.aboutlay2.setObjectName("aboutlay2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.aboutlay2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aboutlogo = QtWidgets.QLabel(self.aboutlay2)
        self.aboutlogo.setAlignment(QtCore.Qt.AlignCenter)
        self.aboutlogo.setObjectName("aboutlogo")
        self.horizontalLayout_3.addWidget(self.aboutlogo)
        self.aboutinfo = QtWidgets.QLabel(self.aboutlay2)
        self.aboutinfo.setObjectName("aboutinfo")
        self.horizontalLayout_3.addWidget(self.aboutinfo)
        self.aboutlay.addWidget(self.aboutlay2)
        self.aboutlay3 = QtWidgets.QWidget(about)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutlay3.sizePolicy().hasHeightForWidth())
        self.aboutlay3.setSizePolicy(sizePolicy)
        self.aboutlay3.setMinimumSize(QtCore.QSize(0, 50))
        self.aboutlay3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.aboutlay3.setObjectName("aboutlay3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.aboutlay3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.aboutclose = QtWidgets.QPushButton(self.aboutlay3)
        self.aboutclose.setMinimumSize(QtCore.QSize(120, 0))
        self.aboutclose.setMaximumSize(QtCore.QSize(120, 16777215))
        self.aboutclose.setObjectName("aboutclose")
        self.horizontalLayout_2.addWidget(self.aboutclose)
        self.aboutlay.addWidget(self.aboutlay3)
        self.horizontalLayout.addLayout(self.aboutlay)

        self.retranslateUi(about)
        self.aboutclose.clicked.connect(about.close)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "Form"))
        self.aboutlogo.setText(_translate("about", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">LOGO</span></p></body></html>"))
        self.aboutinfo.setText(_translate("about", "<html><head/><body><p>版本号：0.0.0.201111</p><p><br/>图像处理与信息安全实验室</p></body></html>"))
        self.aboutclose.setText(_translate("about", "确定"))
